name: build AdoptOpenJDK
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'AdoptOpenJDK/AdoptOpenJDK-8/**'
      - 'AdoptOpenJDK/AdoptOpenJDK-11/**'
      - 'AdoptOpenJDK/AdoptOpenJDK-16/**'
      - 'AdoptOpenJDK/AdoptOpenJDK-17/**'
      - 'AdoptOpenJDK/AdoptOpenJDK-18/**'
      - 'AdoptOpenJDK/AdoptOpenJDK-19/**'
      - 'AdoptOpenJDK/AdoptOpenJDK-20/**'
      - 'AdoptOpenJDK/AdoptOpenJDK-21/**'
jobs:
  push:
    name: "yolks:adopt-open-jdk-${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '8'
          - '11'
          - '16'
          - '17'
          - '18'
          - '19'
          - '20'
          - '21'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUBTOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./AdoptOpenJDK/AdoptOpenJDK-${{ matrix.tag }}
          file: ./AdoptOpenJDK/AdoptOpenJDK-${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/jumala9163/yolks:adopt-open-jdk-${{ matrix.tag }}