name: build Amazon-Corretto-JP
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Amazon-Corretto/Amazon-Corretto-8_JP/**'
      - 'Amazon-Corretto/Amazon-Corretto-11_JP/**'
      - 'Amazon-Corretto/Amazon-Corretto-16_JP/**'
      - 'Amazon-Corretto/Amazon-Corretto-17_JP/**'
      - 'Amazon-Corretto/Amazon-Corretto-18_JP/**'
      - 'Amazon-Corretto/Amazon-Corretto-19_JP/**'
      - 'Amazon-Corretto/Amazon-Corretto-20_JP/**'
      - 'Amazon-Corretto/Amazon-Corretto-21_JP/**'
jobs:
  push:
    name: "yolks:amazon-corretto-${{ matrix.tag }}_jp"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '8_jp'
          - '11_jp'
          - '16_jp'
          - '17_jp'
          - '18_jp'
          - '19_jp'
          - '20_jp'
          - '21_jp'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUBTOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./Amazon-Corretto-JP/Amazon-Corretto-${{ matrix.tag }}_JP
          file: ./Amazon-Corretto-JP/Amazon-Corretto-${{ matrix.tag }}_JP/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/jumala9163/yolks:amazon-corretto-${{ matrix.tag }}_jp