name: build Generic_Go
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Generic/Go/Go-1.20/**'
      - 'Generic/Go/Go-1.21/**'
      - 'Generic/Go/Go-1.22/**'
      - 'Generic/Go/Go-1.23/**'
      - 'Generic/Go/Go-1.24/**'
      - 'Generic/Go/Go-1.25/**'
jobs:
  push:
    name: "yolks:go-${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '1.20'
          - '1.21'
          - '1.22'
          - '1.23'
          - '1.24'
          - '1.25'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUBTOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./Generic/Go/Go-${{ matrix.tag }}
          file: ./Generic/Go/Go-${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/jumala9163/yolks:go-${{ matrix.tag }}