name: build IBM-Semeru-Runtimes
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'IBM-Semeru-Runtimes/IBM-Semeru-Runtimes-8/**'
      - 'IBM-Semeru-Runtimes/IBM-Semeru-Runtimes-11/**'
      - 'IBM-Semeru-Runtimes/IBM-Semeru-Runtimes-16/**'
      - 'IBM-Semeru-Runtimes/IBM-Semeru-Runtimes-17/**'
      - 'IBM-Semeru-Runtimes/IBM-Semeru-Runtimes-18/**'
jobs:
  push:
    name: "yolks:ibm-semeru-runtimes-${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '8'
          - '11'
          - '16'
          - '17'
          - '18'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUBTOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./IBM-Semeru-Runtimes/IBM-Semeru-Runtimes-${{ matrix.tag }}
          file: ./IBM-Semeru-Runtimes/IBM-Semeru-Runtimes-${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jumala9163/yolks:ibm-semeru-runtimes-${{ matrix.tag }}