name: build Impostor
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Impostor/**'
jobs:
  push:
    name: "yolks:impostor"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUBTOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./Impostor
          file: ./Impostor/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jumala9163/yolks:impostor