name: build OpenJDK
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'OpenJDK/OpenJDK-8/**'
      - 'OpenJDK/OpenJDK-11/**'
      - 'OpenJDK/OpenJDK-16/**'
      - 'OpenJDK/OpenJDK-17/**'
      - 'OpenJDK/OpenJDK-18/**'
      - 'OpenJDK/OpenJDK-19/**'
      - 'OpenJDK/OpenJDK-20/**'
      - 'OpenJDK/OpenJDK-21/**'
jobs:
  push:
    name: "yolks:open-jdk-${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '8'
          - '11'
          - '16'
          - '17'
          - '18'
          - '19'
          - '20'
          - '21'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUBTOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./OpenJDK/OpenJDK-${{ matrix.tag }}
          file: ./OpenJDK/OpenJDK-${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jumala9163/yolks:open-jdk-${{ matrix.tag }}